E-learning platform/Models/VideoViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace E_learning_platform.Models
{
    public class VideoAddViewModel
    {
        public int Id { get; set; }
        [Required]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "Nazwa")]
        public string Name { get; set; }

        [Display(Name = "Plik wideo")]
        [DataType(DataType.Upload)]
        public HttpPostedFileBase Video { get; set; }

        [Required]
        public int CourseId { get; set; }
    }

    public class VideoDetailsViewModel
    {
        public string Name { get; set; }
        public string Path { get; set; }
        public int CourseId { get; set; }
    }

    public class VideoDeleteViewModel
    {
        [Required]
        public int Id { get; set; }
        public string Name { get; set; }
        [Required]
        public int CourseId { get; set; }
    }
}

E-learning platform/Controllers/VideoController.cs
using E_learning_platform.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace E_learning_platform.Controllers
{
    [Authorize]
    public class VideoController : BaseController
    {
        public ActionResult Index()
        {
            return View("Error");
        }
        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Add(int? id)
        {
            if (id == null)
                return View("Error");
            var course = await db.Courses.FindAsync(id);
            if (course == null)
                return View("Error");
            return View(new VideoAddViewModel() { CourseId = course.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Add(VideoAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                var file = model.Video;
                var video = new Video() { Name = model.Name, Order = 1, Course = db.Courses.Find(model.CourseId) };
                db.Videos.Add(video);
                await db.SaveChangesAsync();
                int id = video.Course.Id;
                var path = AddCourseFile(file, "video", "Videos", id);
                if (path != null)
                {
                    video.Path = path;
                    await db.SaveChangesAsync();
                }
                return RedirectToAction("View", "Course", new { id = model.CourseId });
            }
            return View(model);
        }
        public async Task<ActionResult> View(int? id)
        {
            if (id == null)
                return View("Error");
            var video = await db.Videos.FindAsync(id);
            if (video == null)
                return View("Error");
            return View(new VideoDetailsViewModel() { Name = video.Name, Path = "/Content/Uploads/" + video.Path, CourseId = video.Course.Id });
        }

        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
                return View("Error");
            var video = await db.Videos.FindAsync(id);
            if (video == null)
                return View("Error");
            return View(new VideoAddViewModel()
            {
                Id = video.Id,
                Name = video.Name,
                CourseId = video.Course.Id
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Edit(VideoAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                var video = await db.Videos.FindAsync(model.Id);
                if (video == null)
                    return View("Error");
                video.Name = model.Name;
                var file = model.Video;
                var path = AddCourseFile(file, "video", "Videos", video.Course.Id);
                if (path != null)
                {
                    video.Path = path;
                }
                await db.SaveChangesAsync();
                return RedirectToAction("View", "Course", new { id = model.CourseId });
            }
            return View(model);
        }

        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
                return View("Error");
            var video = await db.Videos.FindAsync(id);
            if (video == null)
                return View("Error");
            return View(new VideoDeleteViewModel()
            {
                Name = video.Name,
                Id = video.Id,
                CourseId = video.Course.Id
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Delete(AnnouncementDeleteViewModel model)
        {
            if (ModelState.IsValid)
            {
                var video = await db.Videos.FindAsync(model.Id);
                if (video == null)
                    return View("Error");
                db.Videos.Remove(video);
                await db.SaveChangesAsync();
                return RedirectToAction("View", "Course", new { id = model.CourseId });
            }
            return View(model);
        }
    }
}

E-learning platform/Views/Video/Add.cshtml
@model E_learning_platform.Models.VideoAddViewModel

@{
    ViewBag.Title = "Dodaj film";
}

<h2>Prezentacja</h2>

@using (Html.BeginForm("Add", "Video", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Dodaj</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Video, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Video, htmlAttributes: new { @class = "form-control", @type = "File" })
                @Html.ValidationMessageFor(model => model.Video, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.CourseId)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć", "View", "Course", new { id = Model.CourseId }, null)
</div>

E-learning platform/Views/Video/Delete.cshtml
@model E_learning_platform.Models.VideoDeleteViewModel

@{
    ViewBag.Title = "Usuń wideo";
}

<h2>Wideo</h2>

<h3>Usuń</h3>
<div>
    <h4>Czy na pewno chcesz usunąć wideo?</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CourseId)
        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Wróć", "View", "Course", new { id = Model.CourseId }, null)
        </div>
    }
</div>

E-learning platform/Views/Video/Edit.cshtml
@model E_learning_platform.Models.VideoAddViewModel

@{
    ViewBag.Title = "Edytuj film";
}

<h2>Prezentacja</h2>

@using (Html.BeginForm("Edit", "Video", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edytuj</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Video, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Video, htmlAttributes: new { @class = "form-control", @type = "File" })
                @Html.ValidationMessageFor(model => model.Video, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.CourseId)
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć", "View", "Course", new { id = Model.CourseId }, null)
</div>

E-learning platform/Views/Video/View.cshtml
@model E_learning_platform.Models.VideoDetailsViewModel

@{
    ViewBag.Title = Model.Name;
}

<h2>@Model.Name</h2>

<div>
    <div class="embed-responsive embed-responsive-16by9">
        <video width="860" height="480" controls>
            <source src="@Model.Path">
            Twoja przeglądarka nie obsługuje filmów wideo
        </video>
    </div>
</div>
<p>
    @Html.ActionLink("Wróć", "View", "Course", new { id = Model.CourseId }, null)
</p>