E-learning platform/Models/FileViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace E_learning_platform.Models
{
    public class FileAddViewModel
    {
        public int Id { get; set; }
        [Required]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "Nazwa")]
        public string Name { get; set; }

        [Display(Name = "Plik")]
        [DataType(DataType.Upload)]
        public HttpPostedFileBase File { get; set; }

        [Required]
        public int CourseId { get; set; }
    }

    public class FileDeleteViewModel
    {
        [Required]
        public int Id { get; set; }
        [Display(Name = "Nazwa")]
        public string Name { get; set; }
        [Required]
        public int CourseId { get; set; }
    }
}

E-learning platform/Controllers/FileController.cs
using E_learning_platform.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mime;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace E_learning_platform.Controllers
{
    [Authorize]
    public class FileController : BaseController
    {
        public ActionResult Index()
        {
            return View("Error");
        }
        public async Task<ActionResult> Download(int? id)
        {
            if (id == null)
                return View("Error");
            var file = await db.Files.FindAsync(id);
            if (file == null)
                return View("Error");
            var fullPath = Path.Combine(Server.MapPath("~/Content/Uploads"), file.Path);
            return File(fullPath, MediaTypeNames.Application.Octet, Path.GetFileName(fullPath));
        }
        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Add(int? id)
        {
            if (id == null)
                return View("Error");
            var course = await db.Courses.FindAsync(id);
            if (course == null)
                return View("Error");
            return View(new FileAddViewModel() { CourseId = course.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Add(FileAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                var file = model.File;
                var cFile = new CFile() { Name = model.Name, Order = 1, Course = db.Courses.Find(model.CourseId) };
                db.Files.Add(cFile);
                await db.SaveChangesAsync();
                int id = cFile.Course.Id;
                var path = AddCourseFile(file, "file", "Files", id);
                if (path != null)
                {
                    cFile.Path = path;
                    await db.SaveChangesAsync();
                }             
                return RedirectToAction("View", "Course", new { id = model.CourseId });
            }
            return View(model);
        }

        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
                return View("Error");
            var file = await db.Files.FindAsync(id);
            if (file == null)
                return View("Error");
            return View(new FileAddViewModel()
            {
                Id = file.Id,
                Name = file.Name,
                CourseId = file.Course.Id
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Edit(FileAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                var file = await db.Files.FindAsync(model.Id);
                if (file == null)
                    return View("Error");
                file.Name = model.Name;
                var postedFile = model.File;
                var path = AddCourseFile(postedFile, "file", "Files", file.Course.Id);
                if (path != null)
                {
                    file.Path = path;
                }
                await db.SaveChangesAsync();
                return RedirectToAction("View", "Course", new { id = model.CourseId });
            }
            return View(model);
        }

        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
                return View("Error");
            var file = await db.Files.FindAsync(id);
            if (file == null)
                return View("Error");
            return View(new FileDeleteViewModel()
            {
                Name = file.Name,
                Id = file.Id,
                CourseId = file.Course.Id
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Delete(FileDeleteViewModel model)
        {
            if (ModelState.IsValid)
            {
                var file = await db.Files.FindAsync(model.Id);
                if (file == null)
                    return View("Error");
                db.Files.Remove(file);
                await db.SaveChangesAsync();
                return RedirectToAction("View", "Course", new { id = model.CourseId });
            }
            return View(model);
        }
    }
}

E-learning platform/Views/File/Add.cshtml
@model E_learning_platform.Models.FileAddViewModel

@{
    ViewBag.Title = "Dodaj plik";
}

<h2>Plik</h2>

@using (Html.BeginForm("Add", "File", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Dodaj</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.File, htmlAttributes: new { @class = "form-control", @type = "File" })
                @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.CourseId)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć", "View", "Course", new { id = Model.CourseId }, null)
</div>

E-learning platform/Views/File/Delete.cshtml
@model E_learning_platform.Models.FileDeleteViewModel

@{
    ViewBag.Title = "Usuń plik";
}

<h2>Plik</h2>

<h3>Usuń</h3>
<div>
    <h4>Czy na pewno chcesz usunąć plik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CourseId)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
           @Html.ActionLink("Wróć", "View", "Course", new { id = Model.CourseId }, null)
        </div>
    }
</div>

E-learning platform/Views/File/Edit.cshtml
@model E_learning_platform.Models.FileAddViewModel

@{
    ViewBag.Title = "Edytuj plik";
}

<h2>Plik</h2>

@using (Html.BeginForm("Edit", "File", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edytuj</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.File, htmlAttributes: new { @class = "form-control", @type = "File" })
                @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.CourseId)
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć", "View", "Course", new { id = Model.CourseId }, null)
</div>