E-learning platform/Models/PresentationViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace E_learning_platform.Models
{
    public class PresentationAddViewModel
    {
        public int Id { get; set; }
        [Required]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "Nazwa")]
        public string Name { get; set; }

        [Display(Name = "Plik PowerPoint")]
        [DataType(DataType.Upload)]
        public HttpPostedFileBase Presentation { get; set; }

        [Required]
        public int CourseId { get; set;}
    }

    public class PresentationDetailsViewModel
    {
        public string Name { get; set; }
        public string Path { get; set; }
        public int CourseId { get; set; }
    }

    public class PresentationDeleteViewModel
    {
        [Required]
        public int Id { get; set; }
        public string Name { get; set; }
        [Required]
        public int CourseId { get; set; }
    }
}

E-learning platform/Controllers/PresentationController.cs
using E_learning_platform.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace E_learning_platform.Controllers
{
    [Authorize]
    public class PresentationController : BaseController
    {
        public ActionResult Index()
        {
            return View("Error");
        }
        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Add(int? id)
        {
            if (id == null)
                return View("Error");
            var course = await db.Courses.FindAsync(id);
            if (course == null)
                return View("Error");
            return View(new PresentationAddViewModel() { CourseId = course.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Add(PresentationAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                var file = model.Presentation;
                var presentation = new Presentation() { Name = model.Name, Order = 1, Course = db.Courses.Find(model.CourseId) };
                db.Presentations.Add(presentation);
                await db.SaveChangesAsync();
                int id = presentation.Course.Id;
                var path = AddCourseFile(file, "presentation", "Presentations", id);
                if (path != null)
                {
                    presentation.Path = path;
                    await db.SaveChangesAsync();
                }
                return RedirectToAction("View", "Course", new { id = model.CourseId });
            }
            return View(model);
        }
        public async Task<ActionResult> View(int? id)
        {
            if (id == null)
                return View("Error");
            var presentation = await db.Presentations.FindAsync(id);
            if (presentation == null)
                return View("Error");
            return View(new PresentationDetailsViewModel() { Name = presentation.Name, Path = "Uploads/" + presentation.Path, CourseId = presentation.Course.Id });
        }

        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
                return View("Error");
            var presentation = await db.Presentations.FindAsync(id);
            if (presentation == null)
                return View("Error");
            return View(new PresentationAddViewModel()
            {
                Id = presentation.Id,
                Name = presentation.Name,
                CourseId = presentation.Course.Id
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Edit(PresentationAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                var presentation = await db.Presentations.FindAsync(model.Id);
                if (presentation == null)
                    return View("Error");
                presentation.Name = model.Name;
                var file = model.Presentation;
                var path = AddCourseFile(file, "presentation", "Presentations", presentation.Course.Id);
                if (path != null)
                {
                    presentation.Path = path;
                }
                await db.SaveChangesAsync();
                return RedirectToAction("View", "Course", new { id = model.CourseId });
            }
            return View(model);
        }

        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
                return View("Error");
            var presentation= await db.Presentations.FindAsync(id);
            if (presentation == null)
                return View("Error");
            return View(new PresentationDeleteViewModel()
            {
                Name = presentation.Name,
                Id = presentation.Id,
                CourseId = presentation.Course.Id
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<ActionResult> Delete(PresentationDeleteViewModel model)
        {
            if (ModelState.IsValid)
            {
                var presentation = await db.Presentations.FindAsync(model.Id);
                if (presentation == null)
                    return View("Error");
                db.Presentations.Remove(presentation);
                await db.SaveChangesAsync();
                return RedirectToAction("View", "Course", new { id = model.CourseId });
            }
            return View(model);
        }
    }
}

E-learning platform/Views/Presentation/Add.cshtml
@model E_learning_platform.Models.PresentationAddViewModel

@{
    ViewBag.Title = "Dodaj prezentację";
}

<h2>Prezentacja</h2>

@using (Html.BeginForm("Add", "Presentation", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Dodaj</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Presentation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Presentation, htmlAttributes: new { @class = "form-control", @type = "File" })
                @Html.ValidationMessageFor(model => model.Presentation, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.CourseId)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć", "View", "Course", new { id = Model.CourseId }, null)
</div>

E-learning platform/Views/Presentation/Delete.cshtml
@model E_learning_platform.Models.PresentationDeleteViewModel

@{
    ViewBag.Title = "Usuń prezentacje";
}

<h2>Prezentacja</h2>

<h3>Usuń</h3>
<div>
    <h4>Czy na pewno chcesz usunąc prezentację?</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CourseId)
        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Wróć", "View", "Course", new { id = Model.CourseId }, null)
        </div>
    }
</div>

E-learning platform/Views/Presentation/Edit.cshtml
@model E_learning_platform.Models.PresentationAddViewModel

@{
    ViewBag.Title = "Edytuj prezentację";
}

<h2>Prezentacja</h2>

@using (Html.BeginForm("Edit", "Presentation", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edytuj</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Presentation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Presentation, htmlAttributes: new { @class = "form-control", @type = "File" })
                @Html.ValidationMessageFor(model => model.Presentation, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.CourseId)
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć", "View", "Course", new { id = Model.CourseId }, null)
</div>

E-learning platform/Views/Presentation/View.cshtml
@model E_learning_platform.Models.PresentationDetailsViewModel

@{
    ViewBag.Title = Model.Name;
}

<h2>@Model.Name</h2>

<div>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe src="~/Content/ViewerJS/#../@Model.Path" width="1026" height="793" frameborder="0"></iframe>
    </div>
</div>
<p>
    @Html.ActionLink("Wróć", "View", "Course", new { id = Model.CourseId }, null)
</p>